/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EvaButton {
        /**
          * Indicate if this is a basic button
         */
        "basic": boolean;
        /**
          * Indicate if this is a control button
         */
        "control": boolean;
        /**
          * Indicate if this is a danger button
         */
        "danger": boolean;
        /**
          * Indicate if this is a giant sized button
         */
        "giant": boolean;
        /**
          * Indicate if this is a info button
         */
        "info": boolean;
        /**
          * Indicate if this is a large sized button
         */
        "large": boolean;
        /**
          * Indicate if this is a medium sized button
         */
        "medium": boolean;
        /**
          * Indicate if this is a primary button
         */
        "primary": boolean;
        /**
          * Indicate if this is a small sized button
         */
        "small": boolean;
        /**
          * Indicate if this is a secondary button
         */
        "success": boolean;
        /**
          * Indicate if this is a small sized button
         */
        "tiny": boolean;
        /**
          * Indicate if this is a warning button
         */
        "warning": boolean;
    }
}
declare global {
    interface HTMLEvaButtonElement extends Components.EvaButton, HTMLStencilElement {
    }
    var HTMLEvaButtonElement: {
        prototype: HTMLEvaButtonElement;
        new (): HTMLEvaButtonElement;
    };
    interface HTMLElementTagNameMap {
        "eva-button": HTMLEvaButtonElement;
    }
}
declare namespace LocalJSX {
    interface EvaButton {
        /**
          * Indicate if this is a basic button
         */
        "basic"?: boolean;
        /**
          * Indicate if this is a control button
         */
        "control"?: boolean;
        /**
          * Indicate if this is a danger button
         */
        "danger"?: boolean;
        /**
          * Indicate if this is a giant sized button
         */
        "giant"?: boolean;
        /**
          * Indicate if this is a info button
         */
        "info"?: boolean;
        /**
          * Indicate if this is a large sized button
         */
        "large"?: boolean;
        /**
          * Indicate if this is a medium sized button
         */
        "medium"?: boolean;
        /**
          * Indicate if this is a primary button
         */
        "primary"?: boolean;
        /**
          * Indicate if this is a small sized button
         */
        "small"?: boolean;
        /**
          * Indicate if this is a secondary button
         */
        "success"?: boolean;
        /**
          * Indicate if this is a small sized button
         */
        "tiny"?: boolean;
        /**
          * Indicate if this is a warning button
         */
        "warning"?: boolean;
    }
    interface IntrinsicElements {
        "eva-button": EvaButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "eva-button": LocalJSX.EvaButton & JSXBase.HTMLAttributes<HTMLEvaButtonElement>;
        }
    }
}
